version: '3'

volumes:
  pg_data:
  static:
  media:
services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    expose:
      - "9000"
    volumes:
      - static:/static
      - media:/app/media
  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /static/
    expose:
      - "8000"
    volumes:
      - static:/static
  gateway:
    build: ./nginx/
    ports:
      - 80:80
    volumes:
      - static:/static
      - media:/app/media
